version: '3.1'
services:

  db:
    image: postgres
    container_name: pdz-book-store-micronaut-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pdz-book-store
    volumes:
      - pdz-book-store-data-local:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: pdz-book-store-micronaut-adminer
    restart: always
    ports:
      - 15432:8080
    depends_on:
      - db

  redis:
    image: redis:6-alpine
    container_name: pdz-book-store-micronaut-redis
    ports:
      - 6379:6379

  kafka-cluster:
    image: lensesio/fast-data-dev:2.2
    container_name: pdz-book-store-micronaut-kafka-cluster
    environment:
      ADV_HOST: 127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
      FORWARDLOGS: 0              # No log forwarding to kafka topics
      SAMPLEDATA: 0               # No sample data
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Lenses UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect
      - 9581-9585:9581-9585       # JMX
      - 9092:9092                 # Kafka Broker

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: pdz-book-store-micronaut-elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    container_name: pdz-book-store-micronaut-kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://pdz-book-store-micronaut-elasticsearch:9200
    depends_on:
      - elasticsearch

# permanent storage of data.
# > docker volume rm postgres_pdz-book-store-data-local
volumes:
  pdz-book-store-data-local: