version: '3.1'
services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pdz-book-store
    volumes:
      - pdz-book-store-data-local:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 15432:8080

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

# permanent storage of data.
# > docker volume rm postgres_pdz-book-store-data-local
volumes:
  pdz-book-store-data-local: