micronaut:
  application:
    name: bookStore

# jackson config
jackson:
  property-naming-strategy: SNAKE_CASE

# flyway
flyway:
  datasources:
    default:
      enabled: true
      clean-schema: false
      url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/pdz-book-store`}
      user: ${PG_USERNAME:admin}
      password: ${PG_PASSWORD:admin} # secret
      schemas: pdz
      default-schema: pdz

# micronaut-data-jpa
jpa:
  default:
    packages-to-scan:
      - "com.rafaelbaetapena.adapters.out.persistence.v1.entities"
    properties:
      hibernate:
        show_sql: true

# datasource
datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/pdz-book-store`}
    username: ${PG_USERNAME:admin}
    password: ${PG_PASSWORD:admin} # secret
    driver-class-name: org.postgresql.Driver
    schema-genenerate: NONE
    dialect: POSTGRES

# redis
redis:
  uri: redis://localhost
  ssl: false
  timeout: 30s

# elasticsearch
elasticsearch:
  httpHosts: "http://localhost:9200,http://127.0.0.2:9200"
  request:
    default:
      connect-timeout: 1000
      socket-timeout: 10000